module.exports = {
  HILO_DE_GUARDIA: [
    { Codigo: "LH01", Descripcion: "HG Cortado" },
    { Codigo: "LH02", Descripcion: "HG Deshilachado" },
    { Codigo: "LH04", Descripcion: "G Corrido" },
    { Codigo: "LH04", Descripcion: "HG con Chicote cortado - deshilachado - desprendido"},
    { Codigo: "LH08", Descripcion: "HG con ausencia de Amortiguador" },
    { Codigo: "LH09", Descripcion: "HG con Perno corrido en Morsa" },
    { Codigo: "LH10", Descripcion: "HG con ausencia de U en Morsas" },
    { Codigo: "LH11", Descripcion: "HG con ausencia de Chaveta en Perno de la morsa"},
    { Codigo: "LH12", Descripcion: "HG con U floja en Morsa" },
    { Codigo: "LH14", Descripcion: "HG con Amortiguador dañado" },
    { Codigo: "LH15", Descripcion: "HG con Amortiguador flojo" },
    { Codigo: "LH16", Descripcion: "HG con Morseto con Bulón flojo" },
    { Codigo: "LH18", Descripcion: "HG con Morseto en Bloquete sup. Flojo o desprendido"},
    { Codigo: "LH19", Descripcion: "HG sin Morseto en Bloquete superior" },
    { Codigo: "LH21", Descripcion: "HG con Barqueta floja" },
    { Codigo: "LH23", Descripcion: "Terminal del HG fisurado" },
    { Codigo: "LH24", Descripcion: "HG con Barqueta torcida" },
    { Codigo: "LH25", Descripcion: "Desgaste de morsetería en HG" },
    { Codigo: "LH26", Descripcion: "Bulón desplazado en morsetería de HG" },
    { Codigo: "LH27", Descripcion: "Morsa de HG con elementos faltantes" },
    { Codigo: "LH28", Descripcion: "HG con bieletas torcidas" },
    { Codigo: "LH29", Descripcion: "HG con chaveta deteriorada" },
    { Codigo: "LH31", Descripcion: "Preformado en mal estado" },
    { Codigo: "LH32", Descripcion: "Caja de conexión OPGW en mal estado" },
    { Codigo: "LH33", Descripcion: "Bajada de OPGW en mal estado" },
  ],
};
